version: "3.8"
services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    container_name: frontend
  service1:
    build: ./service1
    ports:
      - "3000:3000"
    container_name: service1
  service2:
    build: ./service2
    ports:
      - "3001:3000"
    container_name: service2
